package constants;

import javafx.util.Pair;

import java.awt.Color;
import java.util.Arrays;
import java.util.List;

public class Constants {
    public static final int OUT_OF_BOARD = -1;
    public static final int BOARD_SIZE_IN_CELLS = 8;
    public static final int MENU_WIDTH = 450;
    public static final int CELL_SIZE = 64;
    public static final int BUTTONS_Y_COORDINATE = 10;
    public static final int BUTTONS_WIDTH = 100;
    public static final int BUTTONS_HEIGHT = 50;
    public static final int START_BUTTON_X = 50;
    public static final int RESTART_BUTTON_X = 180;
    public static final int FORFEIT_BUTTON_X = 310;
    public static final int PLAYERS_NAMES_Y = 100;
    public static final int PLAYERS_NAMES_WIDTH = 200;
    public static final int PLAYERS_NAMES_HEIGHT = 50;
    public static final int PLAYER_ONE_NAME_X = 10;
    public static final int PLAYER_TWO_NAME_X = 300;
    public static final int FONT_SIZE = 30;
    public static final int NULL_CODE = 0;
    public static final int WHITE_FIRST_LINE_Y = 0;
    public static final int WHITE_SECOND_LINE_Y = 1;
    public static final int BLACK_FIRST_LINE_Y = 7;
    public static final int BLACK_SECOND_LINE_Y = 6;
    public static final Color WHITE_COLOR = new Color(255,255,255);
    public static final Color BLACK_COLOR = new Color(0, 0, 0);
    public static final Color VS_COLOR = new Color(0, 0, 0);
    public static final Color MESSAGE_COLOR = new Color(0, 0, 0);
    public static final Color BACKGROUND_COLOR = new Color(112, 247, 255);
    public static final Color WHITE_CELL_COLOR = new Color(255, 206, 158);
    public static final Color BLACK_CELL_COLOR = new Color(209, 139, 71);
    public static final Color CHOSEN_CELL_COLOR = new Color(140, 91, 49);
    public static final Color EMPTY_SLOT_COLOR = new Color(195, 98, 108);
    public static final Color OPPONENT_SLOT_COLOR = new Color(195, 77, 34);
    public static final String VERSUS_STRING = "VS";
    public static final String WHITE_NAME = "WHITE";
    public static final String BLACK_NAME = "BLACK";
    public static final String CHECKMATE = "checkmate";
    public static final String STALEMATE = "stalemate";
    public static final String CHESS_TITLE = "Chess";
    public static final String FONT_NAME = "TimesRoman";
    public static final String WELCOME_MESSAGE = "Press Start";
    public static final String ADDITIONAL_WELCOME_MESSAGE = "Or Change Names";
    public static final String GAME_ALREADY_STARTED = "Game already started";
    public static final String GAME_NOT_STARTED = "Game not started";
    public static final String CHANGE_NOT_NOW = "You cannot change your name during the game";
    public static final String INVALID_NAME = "Invalid name: ";
    public static final String NEW_NAME_FOR = "Please new name for ";
    public static final String EMPTY_STRING = "";
    public static final String WIN = " Win!!";
    public static final String TURN = "'s turn";
    public static final String CHECK = "Check! ";
    public static final String WISH = "! Do you want to restart the game?";
    public static final String SELECT_TITLE = "Please select";
    public static final String FORFEIT = "! Do you want to give up the game?";
    public static final String START_BUTTON = "Start";
    public static final String RESTART = "Restart";
    public static final String FORFEIT_BUTTON_NAME = "Forfeit";
    public static final String BISHOP = "bishop";
    public static final String PAWN = "pawn";
    public static final String KING = "king";
    public static final String KNIGHT = "knight";
    public static final String QUEEN = "queen";
    public static final String ROOK = "rook";
    private static final String DIR_WITH_IMG = "images\\";
    public static final Pair<Integer, Integer> VS_COORDINATES = new Pair<>(200, 200);
    public static final Pair<Integer, Integer> MESSAGE_COORDINATES = new Pair<>(100, 300);
    public static final Pair<Integer, Integer> ADDITIONAL_MESSAGE = new Pair<>(100, 335);
    public static final String BISHOP_WHITE_PATH = DIR_WITH_IMG + "white_bishop.png";
    public static final String BISHOP_BLACK_PATH = DIR_WITH_IMG + "black_bishop.png";
    public static final String KING_WHITE_PATH = DIR_WITH_IMG + "white_king.png";
    public static final String KING_BLACK_PATH = DIR_WITH_IMG + "black_king.png";
    public static final String KNIGHT_WHITE_PATH = DIR_WITH_IMG + "white_knight.png";
    public static final String KNIGHT_BLACK_PATH = DIR_WITH_IMG + "black_knight.png";
    public static final String PAWN_WHITE_PATH = DIR_WITH_IMG + "white_pawn.png";
    public static final String PAWN_BLACK_PATH = DIR_WITH_IMG + "black_pawn.png";
    public static final String ROOK_WHITE_PATH = DIR_WITH_IMG + "white_rook.png";
    public static final String ROOK_BLACK_PATH = DIR_WITH_IMG + "black_rook.png";
    public static final String QUEEN_WHITE_PATH = DIR_WITH_IMG + "white_queen.png";
    public static final String QUEEN_BLACK_PATH = DIR_WITH_IMG + "black_queen.png";
    public static final List<Integer> KNIGHT_POSSIBLE_OFFSET = Arrays.asList(-1, 1, -2, 2);
    public static final List<Integer> PAWN_POSSIBLE_OFFSET = Arrays.asList(1, -1);
    public static final List<Integer> QUEEN_POSSIBLE_OFFSET = Arrays.asList(-1, 1);
    public static final List<Integer> ROOK_POSSIBLE_OFFSET = Arrays.asList(-1, 1);
}
